# MySQL.  Versions 4.1 and 5.0 are recommended.# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: mysql2
  encoding: utf8
  database: behappy
  username: root
  #password: root
  host: 127.0.0.1
  port: 3306

development_pune:
  adapter: mysql2
  encoding: utf8
  database: behappy_pune
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

development_bangalore:
  adapter: mysql2
  encoding: utf8
  database: behappy_bangalore
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: behappy_test
  username: root
  #password: root
  host: 127.0.0.1
  port: 3306